name: Trixie Build
on:
  push:
    branches:
      - feat-build-deb13-amd64
jobs:
  amd64:
    name: Trixie Build (amd64)
    runs-on: ubuntu-latest
    container: debian:trixie-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install packages
        run: |
          apt update
          apt -yq --no-install-suggests --no-install-recommends \
            install appstream libfuse2 libsdl1.2-dev build-essential \
            libboost-dev libyaml-cpp-dev xmlto libsdl-mixer1.2-dev \
            libsdl-image1.2-dev libsdl-gfx1.2-dev cmake git

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: appstream libfuse2 libsdl1.2-dev build-essential libboost-dev libyaml-cpp-dev xmlto libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev cmake git
          version: 1.0

      - name: Compile source code
        run: |
          set -x
          cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr \
            -DDEV_BUILD=OFF -DCPACK_GENERATOR=DEB -DOPENXCOM_TARGET=trixie \
            -DCPACK_DEBIAN_PACKAGE_DEPENDS='libsdl1.2debian (>= 1.2.68-3), libsdl-mixer1.2 (>= 1.2.12-19), libsdl-image1.2 (>= 1.2.12-14), libsdl-gfx1.2-5 (>= 2.0.25-12), 	libc6 (>= 2.34)'
          make -j$(nproc)
          make install DESTDIR=AppDir
          cpack -G DEB
          rm -rf AppDir/usr/share/openxcom/UFO
          rm -rf AppDir/usr/share/openxcom/TFTD
