name: Trixie Build
on:
  push:
    branches:
      - feat-build-deb13-amd64
jobs:
  amd64:
    name: Trixie Build (amd64)
    runs-on: ubuntu-latest
    container: debian:trixie-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup environment
        run: |
          echo "DATEFILE=`git log -1 --date=format:\"%Y_%m_%d_%H%M\" --format=\"%ad\"`" >> $GITHUB_ENV
          echo "DATEVERSION=`git log -1 --date=format:\"%Y-%m-%d %H:%M\" --format=\"%ad\"`" >> $GITHUB_ENV
          echo "CMAKE_BUILD_PARALLEL_LEVEL=`getconf _NPROCESSORS_ONLN 2>/dev/null || getconf NPROCESSORS_ONLN 2>/dev/null || echo 2`" >> $GITHUB_ENV

      - name: Setup version info
        run: |
          sed -i "s/OPENXCOM_VERSION_GIT \"[^\"]*\"/OPENXCOM_VERSION_GIT \" git ${{ env.DATEVERSION }}\"/" src/version.h
          echo "FILENAME=oxce_git_${{ env.DATEFILE }}" >> $GITHUB_ENV

      - name: Install packages
        run: |
          apt update
          apt -yq --no-install-suggests --no-install-recommends \
            install appstream libfuse2 libsdl1.2-dev build-essential \
            libboost-dev libyaml-cpp-dev xmlto libsdl-mixer1.2-dev \
            libsdl-image1.2-dev libsdl-gfx1.2-dev cmake git

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: appstream libfuse2 libsdl1.2-dev build-essential libboost-dev libyaml-cpp-dev xmlto libsdl-mixer1.2-dev libsdl-image1.2-dev libsdl-gfx1.2-dev cmake git
          version: 1.0

      - name: Compile source code
        run: |
          set -x
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr \
            -DDEV_BUILD=OFF -DCPACK_GENERATOR=DEB \
            -DCPACK_DEBIAN_PACKAGE_DEPENDS='libsdl1.2debian (>= 1.2.68-3), libsdl-mixer1.2 (>= 1.2.12-19), libsdl-image1.2 (>= 1.2.12-14), libsdl-gfx1.2-5 (>= 2.0.25-12), 	libc6 (>= 2.34)'
          make -j$(nproc)

      - name: Package
        run: |
          set -x
          cd build
          cpack -G DEB

      - name: Archive artifacts
        uses: actions/upload-artifact@v6
        with:
          name: OXCE-8.5.2-trixie-amd64.deb
          path: Extended-8.5.2---unknown.deb
